### ISSUE TITLE
Tracker Attack Question

### ISSUE THREAD

**Issue by WorkHorseIndustries** [uber/sql-differential-privacy#5]
Unless I'm misunderstand something, re-writing the query instead of creating a differentially private dataset allows for a tracker attack, repeatedly invoking a query that returns a small dataset and then using aggregate queries against that collection of small datasets to glean identifying information. Are there any best practices when using this library to mitigate that risk?

**Comment by noahj** [comment]
The attack you describe is prevented by the privacy budget.

This framework allows specifying the budget (epsilon) allocated to each query. In a real deployment this value comes out of a fixed total privacy budget which is tracked across every query (see comment in [the example code](https://github.com/uber/sql-differential-privacy/blob/master/src/main/scala/examples/ElasticSensitivityExample.scala) for more details). This means that if someone submits many queries, each result will get progressively less accurate as the budget is depleted--this prevents statistical inference attacks, including the averaging attack in your example.

This code does not implement a cumulative privacy budget tracking strategy since such a strategy is highly deployment-specific. In practice the operator of this tool will plug in an appropriate implementation. There are many ways to do this. The simplest approach is to track a single value globally; [our paper](https://arxiv.org/abs/1706.09479) surveys a few more advanced techniques.

**Comment by WorkHorseIndustries** [comment]
Thanks, I appreciate the quick response.
